# Site settings
title: Katlyn Whittenburg
email: katlynwhittenburg@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is where you go to learn about the magical and glorious Katlyn.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katlyn.com" # the base hostname & protocol for your site
twitter_username: KatlynWrites
github_username:  KatlynWhitt

# Build settings
markdown: kramdown
